### ISSUE TITLE
Plugin makes page view times extremely slow

### ISSUE THREAD

**Issue by strk** [sunchaserinfo/wp-libravatar-replace#2]
To the point we had to disable it: https://trac.osgeo.org/osgeo/ticket/2305#comment:7

I'm filing this ticket in the hope the code could be made better, to get libre avatar back

**Comment by sunchaserinfo** [comment]
Added caching for DNS responses using WP Object Cache in 3.3.0

You will probably also need a persistent caching plugin if you don't have one: https://codex.wordpress.org/Class_Reference/WP_Object_Cache#Persistent_Caching
