### ISSUE TITLE
Use pear/services_libravatar instead of sunchaser/services-libravatar ?

### ISSUE THREAD

**Issue by aslakr** [sunchaserinfo/wp-libravatar-replace#4]
Is there a reason for not using  `pear/services_libravatar` directly in 

https://github.com/sunchaserinfo/wp-libravatar-replace/blob/532622c164889a7094ea66b42396692e342ae2df/composer.json#L16

?

**Comment by sunchaserinfo** [comment]
There is one: there was no such package at the time of the last release :D

**Comment by sunchaserinfo** [comment]
Fixed in 3.3.0
